---
title: "lab_5_rh"
author: "Randi Honeycutt"
date: "10/28/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objectives

getting counts for different groups
use lubridate to parse dates
find confidence intervervals and do t tests 
heatmap with geom_title()

```{r, include = FALSE}
# attach packages

library(tidyverse)
library(here)
library(janitor)

```

```{r}

#Import lobster data

lobster_abundance <- read_csv(here::here("data","lobster_abundance.csv"), 
                              na = "-99999") %>% 
  clean_names()
```

Use tidyr::uncount() funtion to expand a frequency distribution 

```{r}

lobster_tidy <- lobster_abundance %>% 
  tidyr::uncount(lobster_count)

```

Now each lobster has its own row, this is tidy format. 

Lets look at this in multiple ways:

```{r}

ggplot(data =  lobster_tidy, aes(x = site, y = size_mm)) +
  geom_jitter(aes(color=site), 
              width = 0.2, 
              alpha = 0.3)

ggplot(data =  lobster_tidy, aes(x = site, y = size_mm)) +
  geom_violin(aes(color=site), 
              alpha = 0.3)

ggplot(data =  lobster_tidy, aes(x = size_mm)) +
  geom_histogram(aes(fill = site)) +
  facet_wrap(~site, scales = "free")

ggplot(data =  lobster_tidy, aes(sample = size_mm)) +
  geom_qq(size = 0.5) + 
  facet_wrap(~site, scales = "free")

```


